AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Creates a Serverless application that subscribes to a ManualApproval step in a CodePipeline so that users can approve or deny the pipeline via email

Globals:
    Function:
        Timeout: 30

Parameters:

  PipelineName:
    Type: String
    Default: ''
    Description: The name of the target pipeline. If this is given, make sure it is correct! The events will silently fail otherwise.

  PipelineExportName:
    Type: String
    Default: ''
    Description: Use this if you prefer importing the PipelineName from the stack that created the Pipeline

  ApprovalTopicExportName:
    Type: String
    Description: The name of the export that will provide the SNS Topic ARN to subscribe to for approvals

  AppConfigPath:
    Type: String
    Description: The SSM path to get application configuration from

  Approvers:
    Type: String
    Description: An e-mail address of someone who can approve test environment

  NotificationSubject:
    Type: String
    Description: The subject text to use when emailing approvers

Rules:
  PipelinePresence:
    Assertions:
      - AssertDescription: Either PipelineName or PipelineExportName must be present
        Assert: !Not
          - !EachMemberEquals
            - [!Ref PipelineExportName, !Ref PipelineName]
            - ""

Conditions:
  # Presence checks need to be on exports, otherwise the import validation step
  # fails before the rules/assertions are evaluated.
  NoPipelineExportName: !Equals
    - !Ref PipelineExportName
    - ''

Resources:
  SNSTopic:
    Type: AWS::SNS::Topic

  SNSTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref SNSTopic
      Protocol: email
      Endpoint: !Ref Approvers

  PipelineApprovalExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        -
          PolicyName: "AllowApprovals"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "codepipeline:PutApprovalResult"
                Resource: !Sub
                  - "arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${ResolvedPipelineName}/*"
                  - ResolvedPipelineName: !If
                    - NoPipelineExportName
                    - !Ref PipelineName
                    - Fn::ImportValue: !Ref PipelineExportName

        -
          PolicyName: "GetAppConfig"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "ssm:GetParametersByPath"
                Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${AppConfigPath}"
        -
          PolicyName: "PublishToApprovers"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "SNS:Publish"
                Resource: !Ref SNSTopic

  NotifyLambda:
    Type: AWS::Serverless::Function
    Properties:
        CodeUri: email_handler/
        Handler: index.notifyHandler
        Runtime: nodejs12.x
        Role: !GetAtt PipelineApprovalExecutionRole.Arn
        Environment:
            Variables:
              APP_CONFIG_PATH: !Ref AppConfigPath
              APP_CONFIG_FORCE_RELOAD: 'false'
        Events:
          SNSTopic:
            Type: SNS
            Properties:
              Topic:
                Fn::ImportValue: !Ref ApprovalTopicExportName

  ApprovalLambda:
    Type: AWS::Serverless::Function
    Properties:
        CodeUri: email_handler/
        Handler: index.approvalHandler
        Runtime: nodejs12.x
        Role: !GetAtt PipelineApprovalExecutionRole.Arn
        Environment:
            Variables:
              APP_CONFIG_PATH: !Ref AppConfigPath
              APP_CONFIG_FORCE_RELOAD: 'false'
        Events:
          ApprovalEndpoint:
            Type: Api
            Properties:
              Path: /approval
              Method: get

  AppConfigTargetPipeline:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "${AppConfigPath}/targetPipeline"
      Type: String
      Value: !If
        - NoPipelineExportName
        - !Ref PipelineName
        - Fn::ImportValue: !Ref PipelineExportName

  AppConfigApprovalAPIUrl:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "${AppConfigPath}/approvalApiUrl"
      Type: String
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

  AppConfigApprovalTopicArn:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "${AppConfigPath}/approvalSnsTopicArn"
      Type: String
      Value: !Ref SNSTopic

  AppConfigApprovers:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "${AppConfigPath}/approvers"
      Type: String
      Value: !Ref Approvers

  AppConfigNotificationSubject:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "${AppConfigPath}/notificationSubject"
      Type: String
      Value: !Ref NotificationSubject
