AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Creates a Lambda that can receive CodePipeline ManualApproval SNS notifications and relay the message to a Slack channel
  with a set of interactive buttons for performing the approval/rejection of that pipeline.
  Only one of these should exist per incoming webhook (channel) in your Slack application.

Globals:
    Function:
        Timeout: 30

Parameters:

  AppConfigPath:
    Type: String
    Description: The SSM path to get application configuration from

Outputs:

  LambdaArn:
    Description: The ARN of the notification lambda created by this stack
    Value: !GetAtt NotifyLambda.Arn
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'LambdaArn']]

  LambdaExecutionRole:
    Description: The ARN of the role that will be used by the notification lambda
    Value: !Ref LambdaExecutionRole
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'LambdaExecutionRole']]

Resources:

  LambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        -
          PolicyName: "GetAppConfig"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "ssm:GetParametersByPath"
                Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${AppConfigPath}"

  NotifyLambda:
    Type: AWS::Serverless::Function
    Properties:
        CodeUri: slack_handler/
        Handler: index.notifyHandler
        Runtime: nodejs12.x
        Role: !GetAtt LambdaExecutionRole.Arn
        Environment:
            Variables:
              APP_CONFIG_PATH: !Ref AppConfigPath
              APP_CONFIG_FORCE_RELOAD: 'false'
