AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Creates a Serverless application that can receive interactive actions from Slack and perform CodePipeline approvals.
  Only one of these should exist per Slack application.

Globals:
    Function:
        Timeout: 30

Parameters:

  AppConfigPath:
    Type: String
    Description: The SSM path to get application configuration from

Outputs:

  LambdaExecutionRole:
    Description: The role that the approval lambda will execute under
    Value: !Ref LambdaExecutionRole
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'LambdaExecutionRole']]

Resources:

  LambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        -
          PolicyName: "GetAppConfig"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "ssm:GetParametersByPath"
                Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${AppConfigPath}"
        -
          PolicyName: "AllowApprovals"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "codepipeline:PutApprovalResult"
                Resource: !Sub "arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:*"

  ApprovalLambda:
    Type: AWS::Serverless::Function
    Properties:
        CodeUri: slack_handler/
        Handler: index.approvalHandler
        Runtime: nodejs12.x
        Role: !GetAtt LambdaExecutionRole.Arn
        Environment:
            Variables:
              APP_CONFIG_PATH: !Ref AppConfigPath
              APP_CONFIG_FORCE_RELOAD: 'false'
        Events:
          ApprovalEndpoint:
            Type: Api
            Properties:
              Path: /approval
              Method: post
