AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Subscribes a Slack-Approval-Bot-Notifier to the SNS topic associated with approval in a CodePipeline.

Parameters:

  PipelineRegion:
    Type: String
    Default: ''
    Description: The region in which the target Pipeline is deployed. If none is given, it will assume the same region

  ApprovalTopicArn:
    Type: String
    Description: The ARN of the SNS topic to subscribe to for approvals

  NotifyStackName:
    Type: String
    Description: The stack name that created the Notification lambda to send approvals to.

Conditions:
  NoPipelineRegion: !Equals
    - !Ref PipelineRegion
    - ''

Resources:
  NotifyLambdaSNSSubscription:
    Type: "AWS::SNS::Subscription"
    Properties:
      Endpoint:
        Fn::ImportValue: !Sub '${NotifyStackName}:LambdaArn'
      Protocol: lambda
      Region: !If
        - NoPipelineRegion
        - !Ref AWS::Region
        - !Ref PipelineRegion
      TopicArn: !Ref ApprovalTopicArn

  NotifyLambdaSNSPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        Fn::ImportValue: !Sub '${NotifyStackName}:LambdaArn'
      Principal: sns.amazonaws.com
      SourceArn: !Ref ApprovalTopicArn
